### ISSUE TITLE
ERROR: `round` has no method matching round(::Type{Int64}, ::Float64)

### ISSUE THREAD

**Issue by zimoun** [Forgotten/Helmholtz_3D#1]
Trying to run the code, I have this error, with:

```
  $ julia test/test_operators_3D.jl 
  $ julia test/reconstruction_test_3D.jl
  $ julia examples/test_3D.jl 
```
And `julia examples/test_gmres.jl` returns:
`ERROR: 'convert' has no method matching convert(::Type{Array{Int64,1}}, ::Array{Int64,2})`

What do I miss ?

Julia version 0.3.2.

**Comment by Forgotten** [comment]
did you try the modular branch or the master?

**Comment by zimoun** [comment]
wouaouw ! after your day, I thought you will have some rest :-) (I'm the guy that asked you about Julia and your code today ;-)

In `modular_branch`, 
 - `example/test_gmres.jl` works.
 - `example/test_3D.jl` fails but it is about Paradiso which it is not installed on my laptop.
 - `example/test+fracture.jl` fails with `modelArray not defined`

And the both files in `test/` fail because `subdomain.jl` seems missing.

Julia version 0.4.5

**Comment by Forgotten** [comment]
Ok I fixed the bugs, and I merged the modular branch agains the master one. 
Now it should be ok. I tested the 3 examples and they seemed to work fine.

**Comment by zimoun** [comment]
`example/test_3D.jl` still failing with the error:
`ERROR: LoadError: ArgumentError: MAT not found in path`

And really nice code.
I will dive more into soon :-)

**Comment by Forgotten** [comment]
Hi, 

I forgot to put an IF statement there. That part is opcional if you want to save the wavefield in a .mat file so you can visualize it in MATLAB. I will correct that ASAP.

**Comment by Forgotten** [comment]
Now it should be ok. :)

**Comment by zimoun** [comment]
It is !! :-)

Really nice. I will play around this... Thank you !
